data:
  features:
    - entry_timing_score
    - exit_timing_score
    - risk_mgmt_score
    - pnl_ratio
    - volatility
    - market_condition
    - volume_profile
  target: return_pct
  validation:
    min_train_size: 100
    test_size: 0.2
    time_series_split: true
data_based_schedule:
  large_dataset:
    performance_monitoring: true
    retrain_every: weekly
    threshold: 2000
  medium_dataset:
    retrain_every: weekly
    threshold: 500
  small_dataset:
    retrain_every: 50
    threshold: 100
  xlarge_dataset:
    drift_detection: true
    retrain_every: biweekly
    threshold: 9999999
model:
  algorithm: xgboost
  auto_tuning:
    cv_folds: 3
    enabled: true
    n_trials: 20
  hyperparameters:
    colsample_bytree: 0.8
    learning_rate: 0.1
    max_depth: 4
    n_estimators: 100
    random_state: 42
    subsample: 0.8
monitoring:
  alerts:
    email: admin@trading-journal.com
    performance_threshold: 0.15
    slack_webhook: ""
  drift_detection:
    method: psi
    threshold: 0.2
    window_size: 100
  metrics:
    - rmse
    - r2_score
    - sharpe_ratio
    - information_ratio
scoring:
  entry_threshold: 80
  hybrid_weight: 0.4
  label_horizon: 1h
  min_confidence: 0.4
  mode: ml
  objective: sharpe
storage:
  backup_retention_days: 30
  data_path: data/training_data
  logs_path: logs
  model_path: data/models
strategy_filter:
  dynamic_threshold: true
  min_score: 90
  rolling_window: 20
update_schedule:
  daily_data_check: true
  emergency_threshold: 0.15
  monthly_full_retrain:
    day: 1
    enabled: true
    time: 03:00
  weekly_retrain:
    day: sunday
    enabled: true
    time: 02:00
